name: Auto Delete Branch

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    types: [closed]
    branches:
      - 'develop'

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  # 只在PR被合并时执行，而不是被关闭
    steps:
      - name: Delete feature or hotfix branch
        run: |
          # 获取源分支名称
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
          echo "Processing branch: $SOURCE_BRANCH"
          
          # 检查是否是 feature 或 hotfix 分支
          if [[ $SOURCE_BRANCH =~ ^(feature|hotfix)/ ]]; then
            echo "Deleting branch: $SOURCE_BRANCH"
            curl -X DELETE \
              -H "Authorization: Bearer ${{ github.token }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$SOURCE_BRANCH"
            
            echo "Branch $SOURCE_BRANCH has been deleted"
          else
            echo "Branch $SOURCE_BRANCH is not a feature or hotfix branch, skipping deletion"
          fi 