name: Deploy to Server

on:
  push:
    branches:
      - feature/deploy-ci

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Deploy  # 指定环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_PATH: ${{ secrets.SERVER_PATH }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh $SERVER_USER@$SERVER_HOST "rm -rf $SERVER_PATH/frontend/*"
        sshpass -p "$SSH_PASSWORD" rsync -avz dist/ $SERVER_USER@$SERVER_HOST:$SERVER_PATH/frontend
        sshpass -p "$SSH_PASSWORD" ssh $SERVER_USER@$SERVER_HOST "cd $SERVER_PATH && ./refresh.sh"